language: csharp
services: mysql
solution: cs-sdx.sln
install:
  - nuget restore cs-sdx.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=TravisCI cs-sdx.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./UnitTest/bin/TravisCI/UnitTest.dll