page:
  - pc:
      url: /{area:(yoshiwara|kanagawa)}/gal/

    sp:
      url: /sp/{area:(yoshiwara|kanagawa)}/gal/
      query:
          tag:  cute
    mb:
      url: /m/{area:(yoshiwara|kanagawa)}/gal/
      query:
          tag:  button
  - 
    query_match:
          tag:  
          test:  
  
    pc:
      url: /{area:(yoshiwara|kanagawa)}/shop/
      query:
          tag:  tg_prices_high
          test:  button

    sp:
      url: /sp/{area:(yoshiwara|kanagawa)}/shop/
      query:
          tag:  tg_high

    mb:
      url: /m/{area:(yoshiwara|kanagawa)}/shop/
      query:
          tag:  tg_price