page:
  - pc:
      url: /{area:(yoshiwara|kanagawa)}/gal/

    sp:
      url: /sp/{area:(yoshiwara|kanagawa)}/gal/
      query:
          tag:  cute
    mb:
      url: /m/{area:(yoshiwara|kanagawa)}/gal/
      query:
          tag:  button
  - 
    query_match:
          tg_prices_high:
          button:

    exclude_build_query: [m]

    pc:
      url: /{area:(yoshiwara|kanagawa)}/shop/
      exclude_build_query: [foo,bar]

    sp:
      url: /sp/{area:(yoshiwara|kanagawa)}/shop/
      exclude_build_query: [p]

    mb:
      url: /m/{area:(yoshiwara|kanagawa)}/shop/